id: P2BC96978
initial_creation_type: input
source_metadata:
  title: Namkha Tsewang Chokdrup Series
  language: bo
  description: 'Texts by and about Namkha Tsewang Chokdrup (nam mkha’ tshe dbang mchog
    grub, b. 1744) of Dzogchen Monastery:'
  volume:
    222d693ff3c8469490b8df461d77d5e0:
      title: The Prayer for the Wrathful Guru Takhyung Barwa from the Heart Essence
        of the Vast Expanse
      parent: Prayers
created_at: '2022-03-01T00:58:54.049633'
last_modified_at: '2022-03-01T00:58:54.049636'
statistics:
  total_words: 161
  total_non_words: 12
quality:
  non_words_ratio: 0.07
